// Verified case bank: general clinical-knowledge teaching scenarios -- pharmacogenomics,
// toxicology, hematology, and single-teaching-point crisis vignettes (drug interactions,
// syndrome-specific emergencies). Split out from MillersCases.js (2026-07) because these
// cases, unlike the ones that stayed there, aren't traceable to any specific Miller's
// Anesthesia chapter/page citation -- see the header comment in MillersCases.js for the
// full audit reasoning behind the split.
//
// This is NOT a "less trustworthy" bank: every distinctive physiology flag these cases set
// (hasWPW, carcinoidTumor, maoisActive, burnsTBSAPercent, phPresent, hasPreeclampsia,
// meldScore, etc.) is verified to be consumed by a real, working engine in src/engine/ --
// the simulator actually models the claimed pathophysiology live. What's missing is a
// documented source citation, not simulation fidelity.
//
// See docs/case_integration_prompt.md for how new banks get added.

export const GENERAL_KNOWLEDGE_CASE_PRESETS = [
  {
    id: 'von_willebrand_disease',
    name: 'Hematology - Von Willebrand Disease (Type 1, Elective Hip Arthroplasty)',
    specialty: 'Hematology / Orthopedic',
    description: 'Type 1 VWD patient undergoing total hip arthroplasty. Reduced VWF activity → impaired primary hemostasis and mildly reduced Factor VIII. Preoperative DDAVP test dose confirmed responder. Management: DDAVP at induction, regional anesthesia with caution given platelet function, Type & Screen. PFA-100 C-ADP and C-Epi closure times will be abnormal pre-DDAVP.',
    age: 42, sex: 'female', weight: 68, height: 164,
    hr: 72, sys: 118, dia: 72, spo2: 99, rr: 13, temp: 36.8,
    mallampati: 1, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Lateral', procedure: 'Total Hip Arthroplasty',
    ebl: 'Moderate', duration: 120, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 62, gfr: 98,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    hasVWD: true, vwdType: '1', factorVIIIPercent: 35, vwfActivityPercent: 35
  },
  {
    id: 'hemophilia_a',
    name: 'Hematology - Hemophilia A (Moderate, Orthopedic Procedure)',
    specialty: 'Hematology / Orthopedic',
    description: 'Moderate Hemophilia A (FVIII 3%) undergoing knee washout for hemarthrosis. Requires Factor VIII concentrate loading before incision. Monitor Factor VIII levels during case. Risk of acquired inhibitors (~30% of severe cases). Hemostasis critically depends on Factor VIII target >50% before surgery.',
    age: 28, sex: 'male', weight: 78, height: 181,
    hr: 75, sys: 122, dia: 75, spo2: 99, rr: 14, temp: 37.0,
    mallampati: 1, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Knee Joint Washout',
    ebl: 'Low', duration: 45, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 60, gfr: 110,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    hemophiliaA: true, factorVIIIPercent: 3
  },
  {
    id: 'cyp2d6_um_codeine',
    name: 'Pharmacogenomics - CYP2D6 Ultra-Rapid Metabolizer (Codeine Toxicity)',
    specialty: 'Pharmacogenomics / Acute Pain',
    description: 'Patient with CYP2D6 UM phenotype (multiple gene copies) received codeine 30mg PO for post-tonsillectomy pain. Ultra-rapid conversion to morphine → respiratory depression requiring hospitalization. FDA black-box warning scenario. Management: identify UM phenotype, immediately switch to non-CYP2D6-dependent analgesic (hydromorphone, fentanyl, oxymorphone), naloxone support, oxygen.',
    age: 8, sex: 'male', weight: 28, height: 127,
    hr: 48, sys: 88, dia: 55, spo2: 88, rr: 6, temp: 37.1,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Post-Tonsillectomy Pain Management',
    ebl: 'Low', duration: 0, penicillinAllergy: false,
    npoSolids: 2, npoLiquids: 1, ef: 65, gfr: 115,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    cyp2d6Phenotype: 'UM'
  },
  {
    id: 'g6pd_methb',
    name: 'Pharmacogenomics - G6PD Deficiency + Methemoglobinemia',
    specialty: 'Hematology / Toxicology',
    description: 'G6PD-deficient patient developed methemoglobinemia from benzocaine spray during bronchoscopy. SpO2 reads ~85% (MetHb artifact -- true SaO2 is 78%). Standard treatment is METHYLENE BLUE -- but in G6PD deficiency, methylene blue causes oxidative hemolysis! Correct treatment: high-dose IV Vitamin C (ascorbic acid) + 100% oxygen + transfusion if severe.',
    age: 34, sex: 'male', weight: 72, height: 175,
    hr: 110, sys: 100, dia: 65, spo2: 85, rr: 22, temp: 37.2,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Bronchoscopy Recovery',
    ebl: 'Low', duration: 0, penicillinAllergy: false,
    npoSolids: 6, npoLiquids: 2, ef: 65, gfr: 105,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    g6pdDeficiency: true
  },
  {
    id: 'adrenal_crisis',
    name: 'Endocrinology - Perioperative Adrenal Crisis (Chronic Steroid Use)',
    specialty: 'Endocrinology / General Surgery',
    description: 'Patient on chronic prednisone 15 mg/day for 2 years (RA) undergoing colectomy. Did NOT receive stress-dose steroids at induction. Develops refractory hypotension unresponsive to vasopressors during case -- classic perioperative adrenal crisis. Recognition and immediate hydrocortisone IV bolus is the only effective treatment.',
    age: 58, sex: 'female', weight: 74, height: 162,
    hr: 118, sys: 72, dia: 42, spo2: 97, rr: 18, temp: 36.5,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Laparoscopic Colectomy',
    ebl: 'Moderate', duration: 180, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 60, gfr: 82,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    chronicPrednisoneDoseMgPerDay: 15, chronicSteroidDurationWeeks: 104, infectionType: 'mixed_abdominal'
  },
  {
    id: 'turp',
    name: 'Urology - Transurethral Prostate Resection (TURP)',
    specialty: 'Urology',
    description: 'Elderly male undergoing TURP for BPH. Monitor for TURP syndrome (dilutional hyponatremia, volume overload, hypothermia from irrigation fluid absorption). Spinal anesthesia preferred -- early CNS signs of TURP syndrome are only detectable in an awake patient.',
    age: 74, sex: 'male', weight: 82, height: 172,
    hr: 68, sys: 148, dia: 88, spo2: 97, rr: 14, temp: 36.8,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Lithotomy', procedure: 'Transurethral Resection of Prostate',
    ebl: 'Low', duration: 90, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 4, ef: 55, gfr: 72,
    betaBlocker: true, cad: true, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: true, as: false,
    bphSeverity: 0.7
  },
  {
    id: 'sci_autonomic_dysreflexia',
    name: 'SCI - Autonomic Dysreflexia / TURP',
    specialty: 'Urology',
    description: 'Thoracic spinal cord injury (T4) presenting for TURP. At risk for severe autonomic dysreflexia triggered by bladder distension, surgical stimulation, or urinary retention -- a life-threatening hypertensive crisis unique to SCI patients above T6. Untreated, MAP can exceed 200 mmHg.',
    age: 38, sex: 'male', weight: 71, height: 178,
    hr: 55, sys: 98, dia: 60, spo2: 98, rr: 14, temp: 36.9,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Lithotomy', procedure: 'Transurethral Resection of Prostate',
    ebl: 'Low', duration: 75, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 4, ef: 60, gfr: 80,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    hasSpinalCordInjuryAboveT6: true, bphSeverity: 0.5
  },
  {
    id: 'last_regional',
    name: 'Orthopedic - Interscalene Block (LAST Risk)',
    specialty: 'Regional Anesthesia',
    description: 'Shoulder arthroplasty under interscalene brachial plexus block. Bupivacaine 0.5% administered. Risk of local anesthetic systemic toxicity from intravascular injection or peak absorption. Intralipid 20% rescue is available in the facility but must be recognized and initiated promptly (ASRA LAST Checklist).',
    age: 62, sex: 'female', weight: 71, height: 163,
    hr: 72, sys: 128, dia: 78, spo2: 99, rr: 13, temp: 36.9,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Beach Chair', procedure: 'Total Shoulder Arthroplasty',
    ebl: 'Low', duration: 120, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 60, gfr: 88,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false
  },
  {
    id: 'carcinoid_crisis',
    name: 'Oncology - Carcinoid Tumor Resection (Carcinoid Crisis Risk)',
    specialty: 'Oncology / General Surgery',
    description: 'Patient with known ileal carcinoid and hepatic metastases undergoing liver resection. Carcinoid crisis risk during tumor manipulation: sudden release of serotonin, bradykinin, histamine → profound flushing, bronchospasm, and hemodynamic collapse. Octreotide is THE ONLY effective treatment -- standard vasopressors and antihistamines do NOT block carcinoid mediator release. Pre-treat with octreotide 100 mcg IV bolus before skin incision and have infusion ready.',
    age: 58, sex: 'female', weight: 67, height: 163,
    hr: 78, sys: 125, dia: 72, spo2: 97, rr: 14, temp: 37.0,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Hepatic Metastasectomy (Carcinoid)',
    ebl: 'Moderate', duration: 240, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 58, gfr: 88,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    carcinoidTumor: true, infectionType: 'gram_negative_enteric'
  },
  {
    id: 'laparoscopic_colectomy_complex',
    name: 'Colorectal - Laparoscopic Colectomy (Complex Physiology)',
    specialty: 'Colorectal Surgery',
    description: 'Obese patient with chronic obstructive sleep apnea undergoing laparoscopic sigmoid colectomy. Combined physiologic challenges: steep Trendelenburg + CO2 pneumoperitoneum (IAP 15 mmHg) → elevated ICP, increased airway pressures, reduced CO, compromised venous return, significant CO2 absorption requiring ~20% MV increase. Monitor EtCO2 closely; expect PIPs of 35-40 cmH2O. PneumoperitoneumModel.ts active throughout.',
    age: 56, sex: 'male', weight: 112, height: 178,
    hr: 80, sys: 145, dia: 88, spo2: 96, rr: 14, temp: 36.8,
    mallampati: 3, neckMobility: 'normal', airwayBlood: false,
    obese: true, septic: false, trauma: false, copd: false, chf: false,
    position: 'Trendelenburg', procedure: 'Laparoscopic Sigmoid Colectomy',
    ebl: 'Moderate', duration: 180, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 58, gfr: 85,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: true, as: false,
    pneumoperitoneumActive: true, iapMmHg: 15, infectionType: 'mixed_abdominal'
  },
  {
    id: 'maoi_patient',
    name: 'Psychiatry - MAOI Patient for Emergency Appendectomy',
    specialty: 'Psychiatry / General Surgery',
    description: 'Patient on phenelzine (irreversible MAOI, 14-day washout required) presenting with acute appendicitis requiring emergency appendectomy. The most dangerous drug interaction in anesthesia must be managed: AVOID meperidine (pethidine) → serotonin syndrome; AVOID ephedrine → hypertensive crisis; AVOID indirect sympathomimetics. Use phenylephrine (direct alpha-1) for hypotension. Use fentanyl/remifentanil cautiously (weak serotonin activity vs meperidine). Regional if possible.',
    age: 44, sex: 'female', weight: 65, height: 165,
    hr: 95, sys: 115, dia: 70, spo2: 99, rr: 18, temp: 38.2,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Emergency Appendectomy',
    ebl: 'Low', duration: 60, penicillinAllergy: false,
    npoSolids: 3, npoLiquids: 1, ef: 60, gfr: 95,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    emergentRSI: true, maoisActive: true, maoiWashoutDaysRemaining: 14, infectionType: 'gram_negative_enteric'
  },
  {
    id: 'thoracic_lobectomy_olv',
    name: 'Thoracic - Right Upper Lobe Lobectomy (One-Lung Ventilation)',
    specialty: 'Thoracic Surgery',
    description: 'Patient with RUL lung adenocarcinoma undergoing VATS right upper lobectomy. Requires one-lung ventilation (OLV) via double-lumen tube — the defining anesthetic challenge in thoracic surgery. During OLV: right lung collapses (ventilated = left only), massive obligate right-to-left shunt develops (~50% of pulmonary blood flow, no ventilation). HPV develops over 15 min but is inhibited by volatile agents. OLV management: FiO2 1.0, TV 4-6 mL/kg IBW (left lung only), PEEP 5-8 cmH2O, permissive hypercapnia. SpO2 < 90%: CPAP 5-10 cmH2O to right lung, confirm DLT position by FOB, consider switching to TIVA (IV propofol) to preserve HPV.',
    age: 64, sex: 'male', weight: 78, height: 174,
    hr: 72, sys: 138, dia: 82, spo2: 97, rr: 14, temp: 36.9,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: true, chf: false,
    position: 'Lateral', procedure: 'VATS Right Upper Lobe Lobectomy',
    ebl: 'Moderate', duration: 180, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 52, gfr: 78,
    betaBlocker: true, cad: true, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: true, as: false,
    olvActive: false, olvLateralOperativeLungUp: true, dltInPlace: false,
    infectionType: 'gram_positive_staph'
  },
  {
    id: 'house_fire_co_poisoning',
    name: 'Trauma / Toxicology - House Fire with CO Poisoning + Inhalation Injury',
    specialty: 'Trauma / Burn Surgery',
    description: 'Patient rescued from residential house fire. 35% TBSA burns (2nd/3rd degree), suspected inhalation injury (carbonaceous sputum, singed eyebrows, hoarse voice), and CO poisoning from combustion gases. SpO2 reads FALSELY NORMAL on pulse oximetry — this is the critical teaching point. Actual COHb may be 30-50% from fire exposure duration. Immediate priorities: (1) 100% O2 via tight NRB or ETT (reduces CO half-life from 320 min → 90 min); (2) EARLY INTUBATION before progressive airway edema makes it impossible (inhalation injury + burns cause laryngeal/supraglottic edema over 2-8h); (3) Parkland resuscitation (4 mL × 95 kg × 35% TBSA = 13,300 mL in 24h, half in first 8h); (4) Succinylcholine CONTRAINDICATED after 48h post-burn.',
    age: 42, sex: 'male', weight: 95, height: 180,
    hr: 118, sys: 98, dia: 58, spo2: 97, rr: 22, temp: 37.8,
    mallampati: 3, neckMobility: 'limited', airwayBlood: true,
    obese: false, septic: false, trauma: true, copd: false, chf: false,
    position: 'Supine', procedure: 'Emergent Burn Debridement / Airway Stabilization',
    ebl: 'Moderate', duration: 120, penicillinAllergy: false,
    npoSolids: 0, npoLiquids: 0, ef: 55, gfr: 72,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: true, immobility: false, cp: 'none', htn: false, as: false,
    emergentRSI: true,
    burnsTBSAPercent: 35, hoursPostBurn: 2, inhalationInjury: true, inhalationSeverity: 0.7,
    smokeExposureActive: false, coHb: 38.0, infectionType: 'gram_positive_staph'
  },
  {
    id: 'pah_noncardiac_surgery',
    name: 'Cardiology - Severe PAH for Non-Cardiac Surgery (Highest Perioperative Mortality)',
    specialty: 'Cardiology / Anesthesia',
    description: 'Patient with severe idiopathic PAH (WHO Group 1, mPAP 58 mmHg, PVR 11 Wood units) on dual oral therapy (sildenafil + bosentan) presenting for laparoscopic cholecystectomy. This case has 10-26% reported perioperative mortality in published series. Anesthetic priorities: AVOID all PH triggers (hypoxia, hypercarbia, acidosis, high PEEP, pain, sympathetic activation, N2O). Continue all oral PH medications on day of surgery. Have iNO and inhaled epoprostenol available at the airway. Use vasopressin > norepinephrine for systemic hypotension (less pulmonary vasoconstriction). Milrinone for RV support. Consider epidural to minimize sympathetic stimulation. Monitor: PAC for mPAP/CO/PVR (or TEE for RV function). Prepare for ECMO/RVAD rescue if acute RV failure.',
    age: 38, sex: 'female', weight: 58, height: 162,
    hr: 88, sys: 95, dia: 58, spo2: 92, rr: 18, temp: 36.8,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Laparoscopic Cholecystectomy',
    ebl: 'Low', duration: 90, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 48, gfr: 82,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    phPresent: true, phWhoGroup: 1, phSeverity: 'severe', baselineMpap: 58,
    infectionType: 'gram_negative_enteric'
  },
  {
    id: 'pediatric_infant_inguinal',
    name: 'Pediatrics - 4-Month-Old Infant for Inguinal Herniorrhaphy',
    specialty: 'Pediatric Surgery',
    description: '4-month-old (0.33 years), 6 kg infant for right inguinal hernia repair. CRITICAL PEDIATRIC DIFFERENCES: (1) MAC CORRECTION: Sevoflurane MAC in infants 1-6 months = 3.2% (vs adult 2.0%) — at 2.0% sevo the infant is only ~0.63 MAC (light plane, awareness risk); (2) HR 120-160 is NORMAL — do NOT treat unless < 80 bpm (cardiac output is HR-dependent in infants); (3) Apneic SpO2 drop 4× faster than adults — pre-oxygenate thoroughly; (4) Bradycardia from vagal response is common — have atropine 0.02 mg/kg = 0.12 mg drawn up; (5) Immature CYP3A4 → prolonged fentanyl/midazolam effect; (6) Temperature instability — forced-air warming mandatory.',
    age: 0.33, sex: 'male', weight: 6, height: 62,
    hr: 140, sys: 80, dia: 48, spo2: 99, rr: 40, temp: 37.2,
    mallampati: 1, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Right Inguinal Herniorrhaphy',
    ebl: 'Low', duration: 45, penicillinAllergy: false,
    npoSolids: 4, npoLiquids: 2, ef: 65, gfr: 40,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    infectionType: 'gram_positive_staph'
  },
  {
    id: 'severe_preeclampsia_cs',
    name: 'Obstetrics - Severe Preeclampsia for Emergent Cesarean Section',
    specialty: 'Obstetrics / Maternal-Fetal Medicine',
    description: 'G2P1 at 34 weeks gestation with severe preeclampsia features: sBP 178/112 mmHg, platelets 78,000/μL, AST 148 U/L, ALT 122 U/L, headache, visual changes = HELLP syndrome. Emergent cesarean section required for maternal/fetal deterioration. Critical management decisions: (1) Neuraxial vs. general anesthesia — PLT 78k is at the borderline (most centers proceed with spinal if PLT ≥ 70-80k, no trend to worsen); (2) Magnesium sulfate MUST be running for seizure prophylaxis before neuraxial placement; (3) Antihypertensive to keep sBP < 160 before intubation (labetalol 20mg IV or hydralazine 5mg IV); (4) If GA required: expect exaggerated hypertensive response to laryngoscopy → pre-treat with opioid/esmolol; expect airway edema; have video laryngoscope and surgical airway kit. The Mg-labetalol-neuraxial triad defines excellence in PEC anesthesia.',
    age: 29, sex: 'female', weight: 78, height: 163,
    hr: 96, sys: 178, dia: 112, spo2: 98, rr: 18, temp: 37.1,
    mallampati: 3, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Emergent Cesarean Section (34 wks PEC/HELLP)',
    ebl: 'Moderate', duration: 60, penicillinAllergy: false,
    npoSolids: 2, npoLiquids: 1, ef: 62, gfr: 55,
    betaBlocker: false, cad: false, afib: false, mg: true,
    burns: false, immobility: false, cp: 'none', htn: true, as: false,
    hasPreeclampsia: true, isPregnant: true, gestationalAgeWeeks: 34,
    infectionType: 'gram_negative_enteric'
  },
  {
    id: 'apap_overdose_alf',
    name: 'Toxicology - Acetaminophen Overdose with Evolving Acute Liver Failure',
    specialty: 'Toxicology / Hepatology',
    description: 'Patient took 20g acetaminophen (285 mg/kg) in an intentional overdose 18 hours ago. Now presenting with RUQ pain, nausea, rising transaminases (AST 2,800 U/L, ALT 3,100 U/L), INR 2.4, encephalopathy grade I. Acute liver failure criteria: INR > 1.5 + encephalopathy. Critical decisions: (1) NAC infusion IMMEDIATELY (still effective up to 36h, 150 mg/kg over 1h loading dose); (2) Obtain urgent hepatology/transplant consult + apply King\'s College Criteria for transplant listing (pH < 7.30, OR [PT > 100s + Cr > 3.4 + grade 3-4 encephalopathy]); (3) Monitor glucose hourly (liver failure → hypoglycemia from impaired gluconeogenesis); (4) ICP monitoring if grade 3-4 encephalopathy (cerebral edema = #1 cause of death in ALF); (5) Coagulopathy does NOT need FFP unless bleeding or invasive procedure (INR is a prognostic marker, not a treatment target). No additional APAP in any form.',
    age: 24, sex: 'female', weight: 70, height: 165,
    hr: 108, sys: 95, dia: 58, spo2: 98, rr: 22, temp: 37.4,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Medical Management - APAP Overdose / ALF',
    ebl: 'Low', duration: 0, penicillinAllergy: false,
    npoSolids: 0, npoLiquids: 0, ef: 60, gfr: 48,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    alcoholic: false, malnourished: false,
    infectionType: 'gram_negative_enteric'
  },
  {
    id: 'cemented_total_hip_bcis',
    name: 'Orthopedics - Cemented Total Hip Arthroplasty (BCIS Risk)',
    specialty: 'Orthopedic Surgery',
    description: 'Elderly patient with severe hip osteoarthritis undergoing cemented total hip arthroplasty. BONE CEMENT IMPLANTATION SYNDROME (BCIS) is the critical teaching point: medullary pressurization during cementation forces fat + marrow emboli into the femoral vein → acute RV strain → sudden hypotension, hypoxemia, and cardiac arrest in severe cases. Risk factors: cemented stem (vs cementless), hypovolemia, pre-existing cardiopulmonary disease, pathological bone (cancer/Paget\'s disease). Prevention: irrigate and pressurize-then-suction medullary canal before cement; maintain normovolemia; head-up tilt during cementation to reduce fat embolism load; use cementless implant when feasible. Monitor with TEE — RV dilation/dysfunction is the first sign. Treatment: immediate fluid bolus + vasopressors. Fat Embolism Syndrome may develop 24-48h later (hypoxemia, confusion, petechiae). ISB or spinal anesthesia may be used — ISB phrenic nerve palsy affects ipsilateral hemidiaphragm.',
    age: 74, sex: 'female', weight: 72, height: 158,
    hr: 76, sys: 135, dia: 78, spo2: 97, rr: 14, temp: 36.9,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: true, chf: false,
    position: 'Lateral', procedure: 'Cemented Total Hip Arthroplasty',
    ebl: 'Moderate', duration: 90, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 50, gfr: 62,
    betaBlocker: true, cad: true, afib: false, mg: false,
    burns: false, immobility: true, cp: 'none', htn: true, as: false,
    infectionType: 'gram_positive_staph'
  },
  {
    id: 'high_risk_cardiac_mace',
    name: 'High-Risk Cardiac - Major Abdominal Surgery (MACE/PMI Risk)',
    specialty: 'Cardiac / General Surgery',
    description: 'Patient with established 3-vessel CAD (prior CABG 8 years ago, recent catheterization showing 60% graft disease), EF 35%, T2DM, CKD3 (RCRI score = 5, predicted MACE risk ~15%) presenting for emergent sigmoid colectomy for perforated diverticulitis. Perioperative MI risk is extreme. KEY TEACHING: Rate-Pressure Product (RPP = HR × SBP) drives myocardial O2 demand; Coronary Perfusion Pressure (DBP - LVEDP) drives supply. DUAL GOAL: Keep HR 60-80 (beta-blocker, avoid tachycardia); maintain DBP > 60 (vasopressors over fluids); Hb > 8 (transfuse threshold lowered in active CAD). Even brief tachycardia (HR 120) + hypotension (MAP 55) = Type 2 MI (demand ischemia) in minutes. Troponin will rise in PACU — monitor for MINS (hs-TnT > 14 ng/L). Arterial line mandatory.',
    age: 68, sex: 'male', weight: 88, height: 172,
    hr: 84, sys: 145, dia: 82, spo2: 95, rr: 18, temp: 38.4,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: true, trauma: false, copd: false, chf: true,
    position: 'Supine', procedure: 'Emergency Sigmoid Colectomy (Perforated Diverticulum)',
    ebl: 'High', duration: 180, penicillinAllergy: false,
    npoSolids: 0, npoLiquids: 0, ef: 35, gfr: 48,
    betaBlocker: true, cad: true, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: true, as: false,
    priorMI: true, emergentRSI: true, infectionType: 'mixed_abdominal'
  },
  {
    id: 'thyroid_storm',
    name: 'Endocrine - Thyroid Storm for Emergency Thyroidectomy',
    specialty: 'Endocrine / General Surgery',
    description: 'Patient with uncontrolled Graves\' disease presenting with thyroid storm (Burch-Wartofsky score 65): temperature 39.8°C, HR 162/min, atrial fibrillation, agitation, and acute liver failure secondary to the hypermetabolic state. Emergency thyroidectomy planned after hemodynamic stabilization. TREATMENT CASCADE (in order): (1) PTU 1000 mg PO/NG NOW (blocks synthesis + T4→T3); (2) Wait ≥60 min, THEN Lugol\'s iodide 10 drops q6h (if given first → provides substrate → worsens storm); (3) Propranolol IV to HR < 90 (also blocks T4→T3); (4) Hydrocortisone 100 mg IV q8h; (5) Cooling for hyperthermia; (6) ICU monitoring. Anesthesia: total IV anesthesia (TIVA) preferred; avoid succinylcholine (upregulated AChRs in thyrotoxicosis); avoid desflurane (tachycardia); ketamine avoided (sympathomimetic).',
    age: 34, sex: 'female', weight: 58, height: 163,
    hr: 162, sys: 142, dia: 82, spo2: 95, rr: 24, temp: 39.8,
    mallampati: 3, neckMobility: 'limited', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Emergency Thyroidectomy (Thyroid Storm)',
    ebl: 'Moderate', duration: 90, penicillinAllergy: false,
    npoSolids: 0, npoLiquids: 0, ef: 55, gfr: 60,
    betaBlocker: false, cad: false, afib: true, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    infectionType: 'gram_positive_staph'
  },
  {
    id: 'wpw_cardiac_surgery',
    name: 'Cardiology/Electrophysiology - WPW Syndrome + Cardiac Surgery',
    specialty: 'Cardiac Surgery / Electrophysiology',
    description: 'Patient with known Wolff-Parkinson-White (WPW) syndrome (delta waves on ECG, accessory pathway — Bundle of Kent) presenting for CABG surgery. CRITICAL MANAGEMENT: During surgery, atrial fibrillation (AF) may develop. WPW + AF = LIFE-THREATENING. Standard AF drugs (digoxin, verapamil, diltiazem, adenosine) BLOCK AV NODE only → force all conduction through accessory pathway → RVR 300+ bpm → VF → cardiac arrest. SAFE drugs for WPW + AF: IV procainamide (15 mg/kg over 30 min) or amiodarone; OR immediate synchronized cardioversion. Pre-operative planning: EP study, catheter ablation of accessory pathway recommended before major surgery. If emergency: have procainamide and external defibrillator immediately available. Dental-dose lidocaine does NOT block accessory pathway.',
    age: 44, sex: 'male', weight: 82, height: 178,
    hr: 78, sys: 128, dia: 76, spo2: 98, rr: 14, temp: 36.8,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'CABG (Coronary Artery Bypass Grafting)',
    ebl: 'Moderate', duration: 240, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 2, ef: 42, gfr: 72,
    betaBlocker: true, cad: true, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: true, as: false,
    hasWPW: true, infectionType: 'gram_positive_staph'
  },
  {
    id: 'end_stage_liver_olt',
    name: 'Transplant - End-Stage Liver Disease for OLT (Liver Transplant)',
    specialty: 'Transplant Surgery',
    description: 'Patient with alcoholic cirrhosis (MELD 32, Child-Pugh C) undergoing orthotopic liver transplantation. Three phases: (1) Pre-anhepatic: hyperdynamic circulation (high CO, low SVR from splanchnic vasodilation), severe coagulopathy (INR 3.2), thrombocytopenia (PLT 65k), ascites, hepatopulmonary syndrome (SpO2 88% on room air from intrapulmonary vascular dilations — worsens upright, improves supine: orthodeoxia); (2) ANHEPATIC: IVC/portal clamping → 40-60% ↓venous return → profound hypotension — vasopressors + possibly VVB; no hepatic function → no glucose production (check BG q15 min), no lactate clearance, no citrate metabolism (Ca²⁺ drops with each FFP unit); (3) REPERFUSION: cold hyperkalemic (K⁺ 115-130 mEq/L) preservation solution flushes → sudden hyperkalemia → bradycardia/VF risk; treat with Ca gluconate BEFORE unclamping. Intraoperative monitoring: TEE mandatory (RV function, air), PAC or advanced hemodynamic monitoring, TEG/ROTEM, frequent ABG.',
    age: 52, sex: 'male', weight: 74, height: 172,
    hr: 102, sys: 88, dia: 52, spo2: 88, rr: 22, temp: 37.1,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Orthotopic Liver Transplantation',
    ebl: 'High', duration: 480, penicillinAllergy: false,
    npoSolids: 8, npoLiquids: 4, ef: 60, gfr: 38,
    betaBlocker: false, cad: false, afib: false, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    meldScore: 32, hasHepPulmonarySyndrome: true, oltPhase: 'pre_anhepatic',
    alcoholic: true, infectionType: 'mixed_abdominal'
  },
  {
    id: 'wpw_af_arrest',
    name: 'Emergency - WPW + AF Leading to Cardiac Arrest',
    specialty: 'Emergency / Electrophysiology',
    description: 'Patient with undiagnosed WPW who receives adenosine for "SVT" in the emergency department → within 30 seconds: adenosine blocks AV node → all AF conduction via accessory pathway → RVR 280 bpm → ventricular fibrillation → cardiac arrest. This scenario teaches the most dangerous drug error in emergency arrhythmia management. Rescue: immediate CPR + defibrillation (200J unsynchronized). After return of spontaneous circulation: IV amiodarone or procainamide for rhythm control. Definitive treatment: electrophysiology study + catheter ablation of accessory pathway.',
    age: 28, sex: 'female', weight: 62, height: 167,
    hr: 220, sys: 70, dia: 40, spo2: 88, rr: 28, temp: 37.0,
    mallampati: 2, neckMobility: 'normal', airwayBlood: false,
    obese: false, septic: false, trauma: false, copd: false, chf: false,
    position: 'Supine', procedure: 'Emergency Resuscitation / Cardioversion',
    ebl: 'Low', duration: 30, penicillinAllergy: false,
    npoSolids: 4, npoLiquids: 2, ef: 65, gfr: 98,
    betaBlocker: false, cad: false, afib: true, mg: false,
    burns: false, immobility: false, cp: 'none', htn: false, as: false,
    hasWPW: true, wpwHasAF: true, infectionType: 'gram_negative_enteric'
  }
];

export const GENERAL_KNOWLEDGE_CASE_METADATA = {
  von_willebrand_disease: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Medium',
    duration: 90,
    teachingObjective: 'Preoperative DDAVP administration and monitoring primary hemostasis.',
    challenges: ['Impaired primary platelet adhesion', 'Careful neuraxial contraindications', 'DDAVP response checking']
  },
  hemophilia_a: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Medium',
    duration: 120,
    teachingObjective: 'Factor VIII loading calculations and monitoring secondary hemostasis.',
    challenges: ['Severe factor VIII deficiency', 'Transfusion factor replacement math', 'Monitoring baseline aPTT/TEG']
  },
  cyp2d6_um_codeine: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Hard',
    duration: 60,
    teachingObjective: 'Identifying codeine toxicity in ultra-rapid metabolizers.',
    challenges: ['CYP2D6 ultra-rapid conversion to morphine', 'Pediatric respiratory depression', 'Direct opioid rescue and swap']
  },
  g6pd_methb: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Hard',
    duration: 90,
    teachingObjective: 'Methylene blue contraindication in G6PD deficiency with benzocaine-induced methemoglobinemia.',
    challenges: ['Benzocaine-induced methemoglobinemia', 'Methylene blue oxidative hemolysis risk', 'High-dose Vitamin C / transfusion rescue']
  },
  adrenal_crisis: {
    category: 'Obstetrics & Specialty',
    difficulty: 'Medium',
    duration: 90,
    teachingObjective: 'Hypothalamic-pituitary-adrenal (HPA) axis suppression from chronic steroid therapy.',
    challenges: ['Refractory shock from lack of stress-dose steroids', 'Neglected perioperative hydrocortisone', 'Adrenal crisis recognition']
  },
  turp: {
    category: 'Obstetrics & Specialty',
    difficulty: 'Hard',
    duration: 90,
    teachingObjective: 'TURP syndrome fluid absorption, dilutional hyponatremia, and awake neurological checks.',
    challenges: ['Dilutional hyponatremia', 'Irrigation fluid volume overload', 'Neurological monitoring in spinal anesthesia']
  },
  sci_autonomic_dysreflexia: {
    category: 'Cardiovascular & Hemodynamics',
    difficulty: 'Hard',
    duration: 120,
    teachingObjective: 'Autonomic dysreflexia reflex loop in spinal cord injuries above T6.',
    challenges: ['Severe autonomic dysreflexia reflex loop', 'Hypertensive crisis from bladder/surgical stimulus', 'Vasodilator / deep anesthesia rescue']
  },
  last_regional: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Hard',
    duration: 90,
    teachingObjective: 'Identifying Local Anesthetic Systemic Toxicity (LAST) and initiating Lipid Emulsion rescue.',
    challenges: ['Intravascular bupivacaine injection toxicity', 'Cardiac arrest from local anesthetics', 'Intralipid 20% rescue protocol']
  },
  carcinoid_crisis: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Hard',
    duration: 120,
    teachingObjective: 'Managing carcinoid crisis serotonin storms and octreotide administration.',
    challenges: ['Tumor manipulation serotonin release', 'Severe bronchospasm and flushing', 'Profound shock requiring Octreotide']
  },
  laparoscopic_colectomy_complex: {
    category: 'Airway & Ventilation',
    difficulty: 'Medium',
    duration: 120,
    teachingObjective: 'Steep Trendelenburg positioning and CO2 pneumoperitoneum ventilation shifts.',
    challenges: ['Pneumoperitoneum IAP 15 mmHg compliance drop', 'Steep Trendelenburg positioning ICP surges', 'High peak airway pressures (PIPs)']
  },
  maoi_patient: {
    category: 'Pharmacogenomics & Crisis',
    difficulty: 'Hard',
    duration: 90,
    teachingObjective: 'Irreversible MAOI interactions with sympathomimetics and meperidine.',
    challenges: ['Hypertensive crisis from indirect sympathomimetics', 'Serotonin syndrome from meperidine', 'Direct alpha-1 vasopressor selection']
  },
  thoracic_lobectomy_olv: {
    category: 'Airway & Ventilation',
    difficulty: 'Medium',
    duration: 180,
    teachingObjective: 'Hypoxic pulmonary vasoconstriction (HPV) dynamics and shunt management in double-lumen tubes.',
    challenges: ['Double-lumen tube positioning', 'Right-to-left pulmonary shunt', 'HPV blunting by volatile anesthetics']
  },
  house_fire_co_poisoning: {
    category: 'Obstetrics & Specialty',
    difficulty: 'Hard',
    duration: 120,
    teachingObjective: 'Carbon monoxide oximetry artifact, early intubation, and burn fluid resuscitation.',
    challenges: ['Carbon monoxide oximetry artifact (false high SpO2)', 'Progressive inhalation airway edema', 'Parkland burn fluid calculations']
  },
  pah_noncardiac_surgery: {
    category: 'Cardiovascular & Hemodynamics',
    difficulty: 'Hard',
    duration: 90,
    teachingObjective: 'Avoiding pulmonary hypertensive triggers and managing right ventricular (RV) failure.',
    challenges: ['Idiopathic PAH right ventricular strain', 'Vasopressin selection for coronary perfusion', 'Avoiding hypercarbia/acidosis PH triggers']
  },
  pediatric_infant_inguinal: {
    category: 'Obstetrics & Specialty',
    difficulty: 'Hard',
    duration: 45,
    teachingObjective: 'MAC corrections and cardiac output maintenance in neonatal inguinal herniorrhaphy.',
    challenges: ['Sevoflurane MAC elevated to 3.2%', 'HR-dependent cardiac output', 'Rapid apneic desaturation']
  }
};
