/**
 * DYNAMIC MEDICAL TRUTH DATABASE SNAPSHOT WRAPPER
 * Auto-generated by TokenOptimizer. Maps calls to ClientDbBridge to support
 * synchronous, lag-free search and tests while avoiding Vite bundle bloat.
 */

import { ClientDbBridge } from './ClientDbBridge.ts';
import type { ProseRecord, MatrixRecord } from './ClientDbBridge.ts';

export type { ProseRecord, MatrixRecord };

export const textbookProse: ProseRecord[] = ClientDbBridge.getAllProse();
export const physiologicalMatrices: MatrixRecord[] = ClientDbBridge.getAllMatrices();
