/**
 * DYNAMIC MEDICAL TRUTH DATABASE SNAPSHOT WRAPPER
 * Auto-generated by TokenOptimizer. Maps calls to ClientDbBridge to support
 * synchronous, lag-free search and tests while avoiding Vite bundle bloat.
 */

import { ClientDbBridge } from './ClientDbBridge.ts';
import type { ProseRecord, MatrixRecord } from './ClientDbBridge.ts';

export type { ProseRecord, MatrixRecord };

const manuallyPushedProse: ProseRecord[] = [];

export const textbookProse: ProseRecord[] = new Proxy(manuallyPushedProse, {
  get(target, prop, receiver) {
    ClientDbBridge.getAllProse();
    const mutations = new Set(['push', 'pop', 'shift', 'unshift', 'splice', 'reverse', 'sort']);
    if (typeof prop === 'string' && mutations.has(prop)) {
      const val = Reflect.get(target, prop);
      return typeof val === 'function' ? val.bind(target) : val;
    }
    const list = [...ClientDbBridge.allProse, ...manuallyPushedProse];
    const val = Reflect.get(list, prop);
    return typeof val === 'function' ? val.bind(list) : val;
  },
  set(target, prop, value, receiver) {
    if (prop === 'length') {
      const dbLength = ClientDbBridge.allProse.length;
      const val = Number(value);
      if (!isNaN(val)) {
        target.length = Math.max(0, val - dbLength);
        return true;
      }
    }
    const idx = Number(prop);
    if (!isNaN(idx)) {
      const dbLength = ClientDbBridge.allProse.length;
      if (idx >= dbLength) {
        target[idx - dbLength] = value;
        return true;
      } else {
        ClientDbBridge.allProse[idx] = value;
        return true;
      }
    }
    return Reflect.set(target, prop, value);
  }
}) as any;

const manuallyPushedMatrices: MatrixRecord[] = [];

export const physiologicalMatrices: MatrixRecord[] = new Proxy(manuallyPushedMatrices, {
  get(target, prop, receiver) {
    ClientDbBridge.getAllMatrices();
    const mutations = new Set(['push', 'pop', 'shift', 'unshift', 'splice', 'reverse', 'sort']);
    if (typeof prop === 'string' && mutations.has(prop)) {
      const val = Reflect.get(target, prop);
      return typeof val === 'function' ? val.bind(target) : val;
    }
    const list = [...ClientDbBridge.allMatrices, ...manuallyPushedMatrices];
    const val = Reflect.get(list, prop);
    return typeof val === 'function' ? val.bind(list) : val;
  },
  set(target, prop, value, receiver) {
    if (prop === 'length') {
      const dbLength = ClientDbBridge.allMatrices.length;
      const val = Number(value);
      if (!isNaN(val)) {
        target.length = Math.max(0, val - dbLength);
        return true;
      }
    }
    const idx = Number(prop);
    if (!isNaN(idx)) {
      const dbLength = ClientDbBridge.allMatrices.length;
      if (idx >= dbLength) {
        target[idx - dbLength] = value;
        return true;
      } else {
        ClientDbBridge.allMatrices[idx] = value;
        return true;
      }
    }
    return Reflect.set(target, prop, value);
  }
}) as any;

