/**
 * AUTO-GENERATED MEDICAL TRUTH DATABASE SNAPSHOT
 * Do not edit this file directly. It is compiled automatically during textbook ingestion.
 * Provides synchronous, lag-free, and browser-safe textbook search lookups.
 */

export interface ProseRecord {
  id: string;
  chapter_title: string;
  section_heading: string;
  body_text: string;
}

export interface MatrixRecord {
  id: string;
  archetype: string;
  caption: string;
  structured_payload: string;
}

export const textbookProse: ProseRecord[] = [
  {
    "id": "anesthesia_handbook_chapter_9.pdf_PAGE_001_sec_0",
    "chapter_title": "anesthesia_handbook_chapter_9.pdf",
    "section_heading": "Mechanism of Action of Propofol",
    "body_text": "Propofol induces anesthesia by enhancing GABA-mediated inhibitory neurotransmission. It acts primarily on the GABAA receptor complex in the central nervous system, particularly in the locus ceruleus, causing neural hyperpolarization."
  },
  {
    "id": "anesthesia_handbook_chapter_9.pdf_PAGE_002_sec_0",
    "chapter_title": "anesthesia_handbook_chapter_9.pdf",
    "section_heading": "Cardiovascular Effects of Halothane",
    "body_text": "Halothane reduces cardiac contractility and sensitizes the myocardium to catecholamines. In the locus ceruleus, it causes hyperpolarization via potassium channel activation."
  }
];

export const physiologicalMatrices: MatrixRecord[] = [
  {
    "id": "FIG_09_01",
    "archetype": "COORDINATE X-Y GRAPHS & COMPLEMENTARY PANELS",
    "caption": "Dose-response curve of Propofol-induced neural hyperpolarization",
    "structured_payload": "{\n  \"panels\": [\n    {\n      \"panel_id\": \"A\",\n      \"axes\": {\n        \"x_axis\": {\n          \"label\": \"Propofol concentration\",\n          \"unit\": \"mcg/ml\"\n        },\n        \"y_axis\": {\n          \"label\": \"GABAA Current Enhancement\",\n          \"unit\": \"%\"\n        }\n      },\n      \"mathematical_nature\": \"Sigmoidal/Logarithmic Plateau\",\n      \"curves\": [\n        {\n          \"legend_label\": \"Wildtype GABAA receptors\",\n          \"characteristic_nature\": \"Profound sigmoidal enhancement\"\n        }\n      ],\n      \"coordinate_inflections\": [\n        {\n          \"x_threshold\": \"1.5\",\n          \"y_value_or_change\": \"50%\",\n          \"inflection_description\": \"Half-maximal EC50 enhancement threshold\"\n        }\n      ]\n    }\n  ]\n}"
  }
];
